apiVersion: v1
data:
  CLUSTER_ID: {{.Values.cluster.id | default uuidv4}}
  MANAGEMENT_NAMESPACE: {{.Release.Namespace}}
kind: ConfigMap
metadata:
  name: sapcp-operator-config
  namespace: {{.Release.Namespace}}