apiVersion: v1
kind: Secret
metadata:
  name: sapcp-operator-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.manager.secret.clientid }}
  clientid: {{ .Values.manager.secret.clientid | b64enc | quote }}
  {{- end }}
  {{- if .Values.manager.secret.clientsecret }}
  clientsecret: {{ .Values.manager.secret.clientsecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.manager.secret.url }}
  url: {{ .Values.manager.secret.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.manager.secret.subdomain }}
  subdomain: {{ .Values.manager.secret.subdomain | b64enc | quote }}
  {{- end }}